# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches:
      - main
    paths:
      - 'folder1/**'
      - 'folder2/**'
jobs:
  changes:
    name: Detect Changes in folder
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: Detect Changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          folder1:
            - 'folder1/**'
          folder2:
            - 'folder2/**'
  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.names != '[]' }}
    name:  ${{matrix.name}} - ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        # name: ${{ fromJSON(needs.changes.outputs.names) }}
         environment: [ test,prod]
         node-version: [14.x, 16.x, 18.x]
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
         echo "hello"
    #- run: npm test
